name: gen
description: "A new Flutter package project."
version: 0.0.1
homepage: none

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^2.1.0
  json_annotation: ^4.9.0
  envied: ^1.1.1
  equatable: ^2.0.7
  lottie: ^3.3.1
  
  # for network model
  vexana: ^5.0.3



dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

  very_good_analysis: ^7.0.0
  build_runner: ^2.4.15
  envied_generator: ^1.1.1
  json_serializable: ^6.9.5
  flutter_gen_runner: ^5.10.0

flutter_gen:
  output: lib/src/assets/
  integrations:
    lottie: true
    flutter_svg: true
    image: true

flutter:
  assets:
    - assets/lottie/
    - assets/icons/
    - assets/images/