include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - "/*.g.dart"
    - "*.g.dart"
    - "/*.gen.dart"
    - "test/.test_coverage.dart"
    - "bin/cache/**"
    - "lib/generated_plugin_registrant.dart"
  errors:
    lines_longer_than_80_chars: ignore
linter:
  rules:
  