include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - "**/*.g.dart"  # Exclude all *.g.dart files in any directory
    - "**/*.gen.dart"  # Exclude all *.gen.dart files
    - "test/.test_coverage.dart"
    - "bin/cache/**"
    - "lib/generated_plugin_registrant.dart"
  errors:
    lines_longer_than_80_chars: ignore
    depend_on_referenced_packages: ignore
    flutter_style_todos: ignore
linter:
  rules: