name: flashcard
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8


  #Core
  equatable: ^2.0.7
  get_it: ^8.0.3

  #State
  flutter_bloc: ^9.1.0

  # Config
  easy_localization: ^3.0.7+1


  #Utility
  easy_logger: ^0.0.2
  logging: ^1.3.0
  kartal: ^4.1.0
  google_fonts: ^6.2.1

  #Navigation
  auto_route: ^9.0.0
  #Network Dependencies
  vexana: ^5.0.3


  widgets:
    path: module/widgets

  # Modules
  gen:
    path: module/gen
  common:
    path: module/common
  core:
    path: module/core


dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  auto_route_generator: ^9.0.0
  very_good_analysis: ^7.0.0
  flutter_launcher_icons: ^0.14.3
  device_preview: ^1.2.0
  mockito: ^5.4.2
  bloc_test: ^10.0.0
  patrol: ^3.15.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app/flashcard_logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/app/flashcard_logo.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/app/flashcard_logo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/app/flashcard_logo.png"

flutter:

  uses-material-design: true

  assets:
    - assets/translations/